export const ADD_PLAYER = 'ADD_PLAYER';
export const REMOVE_PLAYER = 'REMOVE_PLAYER';
export const RECEIVE_PLAYER_DETAILS = 'RECEIVE_PLAYER_DETAILS';
export const RECEIVE_PLAYER_LIST = 'RECEIVE_PLAYER_LIST';